server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://47.100.138.188:3306/mynotes?serverTimezone=GMT%2B8&useSSL=FALSE&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml